"""Render a CH4 vibration trajectory as a GIF animation.

Loads the trajectory generated by ``generate_ch4_trajectory.py``
and renders the vibrating methane molecule with ball-and-stick
styling matching the Getting Started documentation example.

Requires: ase, imageio
"""

from pathlib import Path

from ase.io import read

from hofmann import AtomStyle, BondSpec, StructureScene

EXAMPLES_DIR = Path(__file__).resolve().parent
TRAJ = EXAMPLES_DIR / "ch4_md.traj"
OUTPUT = EXAMPLES_DIR / "ch4_md.gif"

traj = read(str(TRAJ), index=":")
print(f"Rendering {len(traj)} frames")

bonds = [
    BondSpec(species=("C", "H"), max_length=1.5, radius=0.055, colour=1.0),
]
atom_styles = {
    "C": AtomStyle(radius=0.5, colour=0.7),
    "H": AtomStyle(radius=0.35, colour=1.0),
}

scene = StructureScene.from_ase(traj, bond_specs=bonds, atom_styles=atom_styles)
scene.render_animation(
    OUTPUT, fps=15, dpi=100, figsize=(4, 4),
)
print(f"Animation saved to {OUTPUT}")
