"""Render an SrTiO3 MD trajectory as a GIF animation.

Loads the trajectory generated by ``generate_srtio3_trajectory.py``
and renders it with TiO6 octahedral polyhedra.

Requires: ase, imageio
"""

from pathlib import Path

from ase.io import read

from hofmann import AtomStyle, BondSpec, PolyhedronSpec, StructureScene

EXAMPLES_DIR = Path(__file__).resolve().parent
TRAJ = EXAMPLES_DIR / "srtio3_md.traj"
OUTPUT = EXAMPLES_DIR / "srtio3_md.gif"

# Load the trajectory (every other frame for a manageable GIF).
traj = read(str(TRAJ), index="::2")
print(f"Rendering {len(traj)} frames")

# Bond and style definitions.
bonds = [
    BondSpec(species=("Ti", "O"), max_length=2.5, complete="*"),
    BondSpec(species=("Sr", "O"), max_length=3.2),
]
polyhedra = [
    PolyhedronSpec(
        centre="Ti",
        colour="steelblue",
        alpha=0.4,
        hide_centre=True,
        hide_bonds=True,
        hide_vertices=True,
    ),
]
atom_styles = {
    "Sr": AtomStyle(radius=1.2, colour="forestgreen"),
    "Ti": AtomStyle(radius=0.8, colour="steelblue"),
    "O": AtomStyle(radius=0.6, colour="firebrick"),
}

# Build the scene and render.
scene = StructureScene.from_ase(
    traj, bond_specs=bonds, polyhedra=polyhedra, atom_styles=atom_styles,
)
scene.render_animation(
    OUTPUT, fps=10, dpi=100, figsize=(6, 6), pbc_padding=1.0,
)
print(f"Animation saved to {OUTPUT}")
