"""Render a CH4 vibration trajectory as a GIF animation.

Loads the trajectory generated by ``generate_ch4_trajectory.py``
and renders the vibrating methane molecule with default styling.

Requires: ase, imageio
"""

from pathlib import Path

from ase.io import read

from hofmann import StructureScene

EXAMPLES_DIR = Path(__file__).resolve().parent
TRAJ = EXAMPLES_DIR / "ch4_md.traj"
OUTPUT = EXAMPLES_DIR / "ch4_md.gif"

# Load the full trajectory.
traj = read(str(TRAJ), index=":")
print(f"Rendering {len(traj)} frames")

# Build the scene with default styling and render.
scene = StructureScene.from_ase(traj)
scene.render_animation(
    OUTPUT, fps=15, dpi=100, figsize=(4, 4),
)
print(f"Animation saved to {OUTPUT}")
