"""Render an SrTiO3 MD trajectory as a GIF animation.

Loads the trajectory generated by ``generate_srtio3_trajectory.py``
and renders a single-layer slice of the TiO6 octahedral network.
Atoms are pre-filtered from the first frame to give a fixed subset
throughout the animation.

Requires: ase, imageio
"""

from pathlib import Path

import numpy as np
from ase.io import read

from hofmann import AtomStyle, BondSpec, PolyhedronSpec, StructureScene

EXAMPLES_DIR = Path(__file__).resolve().parent
TRAJ = EXAMPLES_DIR / "srtio3_md.traj"
OUTPUT = EXAMPLES_DIR / "srtio3_md.gif"

full_traj = read(str(TRAJ), index="::2")
print(f"Loaded {len(full_traj)} frames")

# Select one octahedral layer from the first frame.
ref = full_traj[0]
z = ref.positions[:, 2]
symbols = np.array(ref.get_chemical_symbols())

# In the 4x4x4 supercell (a = 3.905 A), atomic layers along z are:
#   Sr at z ~ 0, 3.9, 7.8, 11.7
#   Ti at z ~ 2.0, 5.9, 9.8, 13.7
#   O  at z ~ 0, 2.0, 3.9, 5.9, 7.8, 9.8, 11.7, 13.7
# Select one Sr plane, one Ti plane, and the three O layers that
# form the TiO6 octahedra (lower apical, equatorial, upper apical).
sr_mask = (symbols == "Sr") & (np.abs(z - 3.9) < 0.5)
ti_mask = (symbols == "Ti") & (np.abs(z - 5.9) < 0.5)
o_mask = (symbols == "O") & (
    (np.abs(z - 3.9) < 0.5)
    | (np.abs(z - 5.9) < 0.5)
    | (np.abs(z - 7.8) < 0.5)
)
indices = np.where(sr_mask | ti_mask | o_mask)[0]
print(f"Selected {len(indices)} atoms for rendering")

traj = [frame[indices] for frame in full_traj]

bonds = [
    BondSpec(species=("Ti", "O"), max_length=2.5),
]
polyhedra = [
    PolyhedronSpec(
        centre="Ti",
        colour="steelblue",
        alpha=0.4,
        hide_centre=True,
        hide_bonds=True,
        hide_vertices=True,
    ),
]
atom_styles = {
    "Sr": AtomStyle(radius=1.2, colour="forestgreen"),
    "Ti": AtomStyle(radius=0.8, colour="steelblue"),
    "O": AtomStyle(radius=0.6, colour="firebrick", visible=False),
}

# Build the scene and render.
scene = StructureScene.from_ase(
    traj, bond_specs=bonds, polyhedra=polyhedra, atom_styles=atom_styles,
)
scene.render_animation(
    OUTPUT, fps=10, dpi=100, figsize=(6, 6),
    show_axes=False, show_cell=False,
    slab_clip_mode="include_whole",
    pbc_padding=1.0,
)
print(f"Animation saved to {OUTPUT}")
