"""Render a CH4 vibration trajectory as a GIF animation.

Loads the trajectory generated by ``generate_ch4_trajectory.py``
and renders the vibrating methane molecule in the XBS visual style.

Requires: ase, imageio
"""

from pathlib import Path

from ase.io import read

from hofmann import AtomStyle, BondSpec, StructureScene

EXAMPLES_DIR = Path(__file__).resolve().parent
TRAJ = EXAMPLES_DIR / "ch4_md.traj"
OUTPUT = EXAMPLES_DIR / "ch4_md.gif"

# Load the full trajectory.
traj = read(str(TRAJ), index=":")
print(f"Rendering {len(traj)} frames")

# XBS-style appearance (matches the Getting Started CH4 example).
bonds = [BondSpec(species=("C", "H"), max_length=1.5, colour=1.0)]
atom_styles = {
    "C": AtomStyle(radius=1.0, colour=0.7),
    "H": AtomStyle(radius=0.7, colour=1.0),
}

scene = StructureScene.from_ase(traj, bond_specs=bonds, atom_styles=atom_styles)
scene.render_animation(
    OUTPUT, fps=15, dpi=100, figsize=(4, 4),
)
print(f"Animation saved to {OUTPUT}")
